### ISSUE TITLE
TypeError: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by LonlyGamerX** [galnir/Master-Bot#10]
when i do the command [p]play url it says in the channel on discord: @user, An error occurred while running the command: TypeError: Cannot read property 'channel' of undefined
You shouldn't ever receive an error like this.
Please contact user
In the txt edition im using it says: (node:22516) DeprecationWarning: Collection#filterArray: use Collection#filter instead

Please note i switch my username for user above

**Comment by JcfeJohn** [comment]
Hello, you can fix this error by changing 
`var voiceChannel = msg.member.voice.channel;`
to 
`var voiceChannel = msg.member.voiceChannel;`

**Comment by galnir** [comment]
@JcfeJohn This bot uses the master branch of discord.js, on master it's `message.member.voice.channel`.
@LonlyGamerX Have you installed discord.js master and commando correctly? When running `npm view discord.js version` you should get **11.5.1**
and you should get **0.10.0** from running `npm view discord.js-commando version`

**Comment by RockyGamerGR** [comment]
I have the same problem please help

**Comment by galnir** [comment]
@RockyGamerGR Did you run in your terminal `npm view discord.js version` and `npm view discord.js-commando version`? What numbers do you get?

**Comment by RockyGamerGR** [comment]
11,5.1 for discord.js
0.10.0 for discord.js commando

**Comment by galnir** [comment]
@RockyGamerGR 
Check if your discord.js and discord.js commando dependencies in your package.json look like this: `    "discord.js": "github:discordjs/discord.js#master",`
`"discord.js-commando": "github:discordjs/Commando"`
If not, replace them with this and hit `npm install`
This solved similar problem to another user

**Comment by RockyGamerGR** [comment]
Thank you very much!!!

**Comment by galnir** [comment]
Great, so @LonlyGamerX you have your solution above. I'm closing this issue, will reopen if this doesn't solve it for you.

**Comment by Boldsen** [comment]
After i edit the dependencies and hit npm install i get these errors:

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by galnir** [comment]
Hey @Boldsen 
This error _usually_ happens when git is not installed or not configured correctly. Have you installed git?
Just run `git version` in your terminal and tell me if you get a git version back.

**Comment by Boldsen** [comment]
I got it working now, think it was because i was missing Git yeah. Thanks!

**Comment by BlueMoon73** [comment]
Sorry for reopening this but I did eveyrthing on here but on my code when I do 
                 let guildMember = message.member 
		 let guild = message.guild
		 let channel = message.member.channel
		 let member = message.member

I get the error            let channel = message.member.channel
                                              ^

TypeError: Cannot read property 'channel' of undefined
    at DiscordClient.<anonymous> (C:\discordbots\testbot2\bot.js:32:33)
    at DiscordClient.emit (events.js:315:20)
    at DiscordClient.handleWSMessage (C:\discordbots\testbot2\node_modules\discord.io\lib\index.js:1854:11)
    at WebSocket.emit (events.js:315:20)
    at Receiver.ontext (C:\discordbots\testbot2\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:371:5)
    at C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.finish (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:541:12)

What should I do, how do I "define" channel?
