### ISSUE TITLE
Music cuts out half way through song

### ISSUE THREAD

**Issue by daneleo** [galnir/Master-Bot#124]
`Error: input stream: Status code: 416
    at ClientRequest.<anonymous> (C:\Users\Dane\musicbot\node_modules\miniget\dist\index.js:156:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)`
i get this when the songs got about half way, is it youtube rate limiting or something, but thats just after playing 1 song

**Comment by galnir** [comment]
Can you fill the issue template first?

**Comment by daneleo** [comment]
Sure thing. Didn't even know there was one, where do I find it?

**Comment by galnir** [comment]
When you open an issue it's already there, just needs to be filled

**Comment by galnir** [comment]
@daneleo I'm closing this, please open another issue and fill the template. I'll be happy to help you :)
