### ISSUE TITLE
i dont see why , tried installing the phyton and node opus but failed

### ISSUE THREAD

**Issue by himekichi** [galnir/Master-Bot#131]
Error: Error: Cannot find module 'C:\Users\gwerz\Downloads\master electric\node_modules\@discordjs\opus\prebuild\node-v72-napi-v3-win32-x64-unknown-unknown\opus.node'
Require stack:
- C:\Users\gwerz\Downloads\master electric\node_modules\@discordjs\opus\lib\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\util\loader.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\Client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\index.js
- C:\Users\gwerz\Downloads\master electric\index.js
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\util\loader.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\Client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\index.js
- C:\Users\gwerz\Downloads\master electric\index.js
Error: Cannot find module 'opusscript'
Require stack:
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\util\loader.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\Client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\index.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\client.js
- C:\Users\gwerz\Downloads\master electric\node_modules\discord.js-commando\src\index.js
- C:\Users\gwerz\Downloads\master electric\index.js
    at Object.loader [as require] (C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\Users\gwerz\Downloads\master electric\node_modules\prism-media\src\opus\Opus.js:135:5)
    at AudioPlayer.playPCMStream (C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\player\BasePlayer.js:53:17)
    at VoiceConnection.play (C:\Users\gwerz\Downloads\master electric\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at C:\Users\gwerz\Downloads\master electric\commands\music\play.js:231:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by himekichi** [comment]
npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.

> ref@1.3.5 install C:\Users\gwerz\Downloads\master electric\node_modules\ref
> node-gyp rebuild


C:\Users\gwerz\Downloads\master electric\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.6.30320.27) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gwerz\Downloads\master electric\node_modules\ref
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> node-opus@0.3.3 install C:\Users\gwerz\Downloads\master electric\node_modules\node-opus
> node-gyp rebuild


C:\Users\gwerz\Downloads\master electric\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.6.30320.27) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gwerz\Downloads\master electric\node_modules\node-opus
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN discord.js-commando@0.11.0-dev requires a peer of @types/better-sqlite3@^5.0.0 but none
is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.11.0-dev requires a peer of better-sqlite3@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.11.0-dev requires a peer of sqlite@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN master-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gwerz\AppData\Roaming\npm-cache\_logs\2020-07-28T11_54_29_502Z-debug.log

**Comment by himekichi** [comment]
neutralized the error with some googling thx
