### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by xD4rKN3sS** [galnir/Master-Bot#15]
I have no idea why I miss this error, could you help me?
Error:
(node:8031) DeprecationWarning: Collection#filterArray: use Collection#filter instead
Running command music:play.
TypeError: Cannot read property 'username' of undefined
    at owners.map (/root/discord-bots/d4rkn3ss/node_modules/discord.js-commando/src/commands/message.js:239:48)
    at Array.map (<anonymous>)
    at CommandMessage.run (/root/discord-bots/d4rkn3ss/node_modules/discord.js-commando/src/commands/message.js:237:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by galnir** [comment]
Have you taken a look at #14?

**Comment by galnir** [comment]
@xD4rKN3sS ?
