### ISSUE TITLE
Can't play video with age limit

### ISSUE THREAD

**Issue by darkpologang777** [galnir/Master-Bot#168]
**Describe the bug**
Impossible to play music with age limit

**To Reproduce**
1. Play a music with age limit

**Expected behavior**
"Can't play this music"

Hosted on VPS, all the modules installed.

**Comment by galnir** [comment]
What error does it emit

**Comment by darkpologang777** [comment]
TypeError: input stream: secondaryResults is not iterable
    at Object.exports.getRelatedVideos (/root/Bot/node_modules/ytdl-core/lib/info-extras.js:130:22)
    at gotConfig (/root/Bot/node_modules/ytdl-core/lib/info.js:156:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.<computed> [as getBasicInfo] (/root/Bot/node_modules/ytdl-core/lib/info.js:297:18)
    at async exports.getFullInfo (/root/Bot/node_modules/ytdl-core/lib/info.js:188:14)
    at async Object.exports.<computed> [as getFullInfo] (/root/Bot/node_modules/ytdl-core/lib/info.js:297:18)

**Comment by galnir** [comment]
Can you send me the link of the video?

**Comment by darkpologang777** [comment]
https://youtu.be/oJi_tNVILM4

**Comment by galnir** [comment]
Update your ytdl-core version to 3.2.1:
```npm i ytdl-core@3.2.1```

that will fix it
