### ISSUE TITLE
hello when i  do play command  i  get error and  it dont play music                            

### ISSUE THREAD

**Issue by yk303** [galnir/Master-Bot#176]
Error: input stream: Status code: 429
2020-08-24T06:22:29.687489+00:00 app[worker.1]:     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:150:31)
2020-08-24T06:22:29.687489+00:00 app[worker.1]:     at Object.onceWrapper (events.js:422:26)
2020-08-24T06:22:29.687490+00:00 app[worker.1]:     at ClientRequest.emit (events.js:315:20)
2020-08-24T06:22:29.687490+00:00 app[worker.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
2020-08-24T06:22:29.687491+00:00 app[worker.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
2020-08-24T06:22:29.687492+00:00 app[worker.1]:     at TLSSocket.socketOnData (_http_client.js:469:22)
2020-08-24T06:22:29.687493+00:00 app[worker.1]:     at TLSSocket.emit (events.js:315:20)
2020-08-24T06:22:29.687493+00:00 app[worker.1]:     at addChunk (_stream_readable.js:295:12)
2020-08-24T06:22:29.687493+00:00 app[worker.1]:     at readableAddChunk (_stream_readable.js:271:9)
2020-08-24T06:22:29.687494+00:00 app[worker.1]:     at TLSSocket.Readable.push (_stream_readable.js:212:10)

**Comment by galnir** [comment]
Installing the latest ytdl-core version should solve this

**Comment by yk303** [comment]
> Installing the latest ytdl-core version should solve this

What the command for it since I also host it some times on vps or heroku

**Comment by galnir** [comment]
npm i ytdl-core@3.2.2

**Comment by yk303** [comment]
> npm i ytdl-core@3.2.2

Thanks. It's working now but not sure it will be working since yesterday it stopped and it was working 24/24 hours

**Comment by galnir** [comment]
It should work, btw this issue isn't related to the bot it's specifically related to the ytdl-core library which the bot uses
