### ISSUE TITLE
Cannot play song

### ISSUE THREAD

**Issue by yk303** [galnir/Master-Bot#248]
error Cannot play song

Ubuntu
 - Node Version(Should be v12 atleast):  yes
 - Are python 2.7 and Ffmpeg installed?: yes
-on vps

**Comment by galnir** [comment]
The console should show an error, does it show one?

**Comment by ModoSN** [comment]
Do you get errors? Any screenshots? Does it only happen to one particular song?

**Comment by yk303** [comment]
All songs don't play them

**Comment by yk303** [comment]
> The console should show an error, does it show one?

nope

**Comment by galnir** [comment]
Did you delete/add code? The next line after the 'cannot play song' message is a console.error call

**Comment by yk303** [comment]
Error: input stream: Could not find player config
    at exports.getBasicInfo (/root/yk-bot/node_modules/ytdl-core/lib/info.js:90:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Map.getOrSet (/root/yk-bot/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/root/yk-bot/node_modules/ytdl-core/lib/info.js:215:14)
    at async Map.getOrSet (/root/yk-bot/node_modules/ytdl-core/lib/cache.js:24:19)

**Comment by galnir** [comment]
@yk303 All you need to do is update ytdl-core.
If you cloned this repo you can use ```git pull``` and then ```npm install``` or you can just ```npm install ytdl-core@3.4.2```

**Comment by yk303** [comment]
ok thx
