### ISSUE TITLE
Stack Errors?  and Others

### ISSUE THREAD

**Issue by Dallatar** [galnir/Master-Bot#289]
I cloned your bot with the new GH CLI program.  Did all the installs (I believe) and when I went to activate the node, I got stack errors relating to some of the .js files in your commando.  Additionally, when I was running the "npm i" I got a screen full of gyp errors relating to the node-gyp.js file.  I have no clue what any of this means.

I remember you had a nice page of a step-by-step of what to do when cloning, installing, etc.  I dont see it anymore.  Can you please re-upload that page and guide of how to install.  I am using windows 10.

**Comment by Bacon-Fixation** [comment]
try powershell or windows command prompt to run the `npm i ` (i have never tried GH CLI to install the bot) 
I am running the current build with Windows 10 
nodejs v14.15.0
python2.7
ffmepg v4.3.1

check and make sure you have python2.7 installed nodejs 12 or higher

**Comment by Dallatar** [comment]
Thank you for the quick response.  I actually do use windows command prompt to run everything; with the same versions as you mentioned for those programs.  Any other thoughts?

**Comment by Bacon-Fixation** [comment]
Is it possible to post the error that pop up?

**Comment by Dallatar** [comment]
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\knf\Desktop\Discord Bots\Roon Bot\node_modules\better-sqlite3
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\knf\AppData\Roaming\npm-cache\_logs\2020-11-13T01_47_34_093Z-debug.log
npm WARN master-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\knf\AppData\Roaming\npm-cache\_logs\2020-11-13T01_47_37_885Z-debug.log

**Comment by Bacon-Fixation** [comment]
@Dallatar 
Open Command in Admin and run

`npm install --global windows-build-tools`

and then retry `npm i`


source : https://github.com/nodejs/node-gyp#on-windows

**Comment by Dallatar** [comment]
And I get these errors when  I try the node index.js

node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'quick.db'
Require stack:
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\commands\music\create-playlist.js
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\node_modules\require-all\index.js
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\node_modules\discord.js-commando\src\registry.js
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\node_modules\discord.js-commando\src\client.js
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\node_modules\discord.js-commando\src\index.js
- C:\Users\knf\Desktop\Discord Bots\Roon Bot\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\knf\Desktop\Discord Bots\Roon Bot\commands\music\create-playlist.js:2:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\commands\\music\\create-playlist.js'[39m,
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\node_modules\\require-all\\index.js'[39m,
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\node_modules\\discord.js-commando\\src\\registry.js'[39m,
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\node_modules\\discord.js-commando\\src\\client.js'[39m,
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\node_modules\\discord.js-commando\\src\\index.js'[39m,
    [32m'C:\\Users\\knf\\Desktop\\Discord Bots\\Roon Bot\\index.js'[39m
  ]
}

**Comment by Bacon-Fixation** [comment]
@Dallatar 
Open Command in Admin and run

`npm install --global windows-build-tools`

and then retry `npm i`


source : https://github.com/nodejs/node-gyp#on-windows

**Comment by Dallatar** [comment]
I do thank you for your responses.  However I do not know what is happening.  I cloned this bot 2 months ago and it worked.  Then it suddenly stopped working this week.  I came here to check and it seemed the code/files changes so I tried to pull the new code and now everything doesn't work.  Maybe I need to delete everything and restart from scratch again.

As I asked earlier, is there another or better way to Clone the bot?

**Comment by Bacon-Fixation** [comment]
it would be best to clone 

i use [Github Desktop](https://desktop.github.com/)

**Comment by galnir** [comment]
Follow my [guide](https://dev.to/galnir/how-to-make-a-discord-music-bot-3c0p). 
You probably didn't install all the required stuff and that's why you're getting these errors. After following my guide also read [this](https://spin.atomicobject.com/2019/03/27/node-gyp-windows/)

**Comment by galnir** [comment]
@Dallatar Let me know if you manage to run the bot properly after following the guide I linked you above

**Comment by Dallatar** [comment]
Yes, hello.  I deleted all my files and started from scratch again following the guides (once more).  This time my Bot was able to join my discord server; however upon trying to play a playlist, this error(s) popped up in my command window...

MinigetError: input stream: Status code: 416
    at ClientRequest.<anonymous> (C:\Users\...........\node_modules\miniget\dist\index.js:197:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10) {
  statusCode: 416
}

And the song/playlist was not able to be played.  I am looking into it.
