### ISSUE TITLE
TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by icsmac** [galnir/Master-Bot#40]
Im hosting my bot in glitch.com
Its working before idk why i get this error

Ready!8:26 PM

Oops! Error: 400 Bad Request8:26 PM

/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/MessageEmbed.js:4338:26 PM

.flat(2)8:26 PM

^8:26 PM

8:26 PM

TypeError: fields.flat is not a function8:26 PM

at Function.normalizeFields (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/MessageEmbed.js:433:8)8:26 PM

at MessageEmbed.setup (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/MessageEmbed.js:68:50)8:26 PM

at new MessageEmbed (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/MessageEmbed.js:11:10)8:26 PM

at embeds.map.e (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/Message.js:101:48)8:26 PM

at Array.map (<anonymous>)8:26 PM

at CommandoMessage._patch (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/Message.js:101:39)8:26 PM

at new Message (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/structures/Message.js:43:20)8:26 PM

at new CommandoMessage (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js-commando/src/extensions/message.js:14:4)8:26 PM

at MessageManager.add (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/managers/BaseManager.js:49:32)8:26 PM

at MessageManager.add (/rbd/pnpm-volume/2fe8ac4a-1d04-4487-bf4a-df3ec67ce89f/node_modules/discord.js/src/managers/MessageManager.js:29:18)

**Comment by galnir** [comment]
discordjs now requires Node v12 at least. Update your Node version

**Comment by icsmac** [comment]
Ok i try it...

**Comment by icsmac** [comment]
It works! Thanks.
