### ISSUE TITLE
Large playlists error

### ISSUE THREAD

**Issue by Kaurobi** [galnir/Master-Bot#44]
I removed the playlist limit however whenever I play a large playlist I get this error:

```
Error: resource youtube#videoListResponse not found
    at C:\Users\Kuba\Desktop\luv\node_modules\simple-youtube-api\src\Request.js:35:68
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PlayCommand.run (C:\Users\Kuba\Desktop\luv\commands\music\play.js:58:25)
    at async CommandoMessage.run (C:\Users\Kuba\Desktop\luv\node_modules\discord.js-commando\src\extensions\message.js:235:20)
    at async CommandDispatcher.handleMessage (C:\Users\Kuba\Desktop\luv\node_modules\discord.js-commando\src\dispatcher.js:143:19)
```

Any help please?

**Comment by galnir** [comment]
Can you provide the playlist link?

**Comment by Kaurobi** [comment]
Sure: https://www.youtube.com/playlist?list=PLvwHxsUPFXE19jMAm2xpMrUUZRdo8Fjku

It's unlisted, I've tried making it public and still the same error.

**Comment by galnir** [comment]
It works for me, I have the 10 song limit, so make sure you didn't remove anything not related to the limit unintentionally

**Comment by galnir** [comment]
Closing since it's a problem on your end and you're not responding
