### ISSUE TITLE
Im having problems when running this bot on a host

### ISSUE THREAD

**Issue by Guest0070** [galnir/Master-Bot#442]
**Describe the bug**
Whenever I try to run this bot this happens 
found 111 vulnerabilities (110 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
/home/container/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/container/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/compiled/12.19.1/linux/x64/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/home/container/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/container/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1015:30) {
  tries: [
    '/home/container/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/compiled/12.19.1/linux/x64/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node'
  ]
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pterodactyl panel
 - Node Version(Should be v12 atleast): Its a host (I don't know what version it is)
 - Are python 2.7 and Ffmpeg installed?: Yeah
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): On a bot hosting company, Dan Bot host which has pterodactyl panel)

**Additional context**

**Comment by galnir** [comment]
I looked up 'Pterodactyl panel' and it isn't an operating system, it's a hosting solution. I have no idea what operating system they use, but it looks like that platform is meant to host game servers

**Comment by Guest0070** [comment]
It's for hosting bots too

**Comment by Guest0070** [comment]
So any help that you can provide?

**Comment by Natemo6348** [comment]
@Guest0070 could you try running `npm rebuild better-sqlite3`? Usually works for me after a couple tries

**Comment by galnir** [comment]
> So any help that you can provide?

This bot requires python 2.7 and a node v12 or newer. I don't know if this 'hosting solution' has them preinstalled and what operating system they use.
Regardless of that try to reinstall your node modules

**Comment by Guest0070** [comment]
Ok will try those things tomorrow :D

**Comment by Guest0070** [comment]
> > So any help that you can provide?
> 
> This bot requires python 2.7 and a node v12 or newer. I don't know if this 'hosting solution' has them preinstalled and what operating system they use.
> Regardless of that try to reinstall your node modules

How to reinstall node modules

**Comment by galnir** [comment]
> > > So any help that you can provide?
> > 
> > 
> > This bot requires python 2.7 and a node v12 or newer. I don't know if this 'hosting solution' has them preinstalled and what operating system they use.
> > Regardless of that try to reinstall your node modules
> 
> How to reinstall node modules

nvm don't uninstall, just run
```npm install```
and 
```npm rebuild better-sqlite3```

**Comment by galnir** [comment]
@Guest0070 If you still can't solve the problem using the solutions we provided, comment here and I'll reopen the issue
