### ISSUE TITLE
A strange issue popped up

### ISSUE THREAD

**Issue by OreoBoat** [galnir/Master-Bot#46]
Hello, first of all, thank you for creating this amazing bot.
I followed your guide based on this [link](https://dev.to/galnir/how-to-make-a-discord-music-bot-3c0p).
And It seems that after running `node index.json`, it returns an error of:
```
internal/modules/cjs/loader.js:1195
    throw err;
    ^

SyntaxError: /home/pi/Master-Bot/config.json: Unexpected token / in JSON at position 20
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1192:22)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/pi/Master-Bot/index.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

**Comment by galnir** [comment]
You probably didn't place a key correctly in config.json

**Comment by galnir** [comment]
Was that the issue?

**Comment by OreoBoat** [comment]
I'm using raspbian, It seems that the js won't run because of the empty block space...
_(Sorry I'm a beginner, I don't know much about js)_
```
{
  "prefix": "!",  // You can change the prefix to whatever you want it doesn't have to be - !
  "token": "Your-Bot-Token",
  "youtubeAPI": "youtube-api-key"
}
```
I compared it with other config, and it seems to be working after deleting the space
```
{
"prefix": "!",  // You can change the prefix to whatever you want it doesn't have to be - !
"token": "Your-Bot-Token",
"youtubeAPI": "youtube-api-key"
}
```

**Comment by galnir** [comment]
Weird, blank space should have no effect
