### ISSUE TITLE
Remove multiple options of songs on “play” command

### ISSUE THREAD

**Issue by muhitrhn** [galnir/Master-Bot#474]
Can you please tell me how can i make the “play” command to play the first result automatically? I don’t want to select from the result, i want the first result to play automatically upon executing command. @galnir @Bacon-Fixation 
![FAD3C95E-52F9-4CDE-A5D2-7D5793F40C59](https://user-images.githubusercontent.com/36473811/111808328-1c221b00-88fe-11eb-8142-0d6f41b22508.jpeg)

**Comment by Bacon-Fixation** [comment]
@muhitrhn I advise it (it can get frustrating)
I made a quick and dirty alteration to play.js that fits your requirements Here

https://github.com/Bacon-Fixation/Beta-Commands/

this alters lines 375 through 510 in play.js

Much Love
-Bacon

**Comment by muhitrhn** [comment]
It threw an error, didn’t seem to work. @Bacon-Fixation 

> 2021-03-20T17:17:27.127465+00:00 app[worker.1]: internal/modules/cjs/loader.js:883
2021-03-20T17:17:27.127507+00:00 app[worker.1]:   throw err;
2021-03-20T17:17:27.127507+00:00 app[worker.1]:   ^
2021-03-20T17:17:27.127507+00:00 app[worker.1]: 
2021-03-20T17:17:27.127508+00:00 app[worker.1]: Error: Cannot find module '../../options.json'
2021-03-20T17:17:27.127508+00:00 app[worker.1]: Require stack:
2021-03-20T17:17:27.127511+00:00 app[worker.1]: - /app/commands/music/play.js
2021-03-20T17:17:27.127512+00:00 app[worker.1]: - /app/node_modules/require-all/index.js
2021-03-20T17:17:27.127512+00:00 app[worker.1]: - /app/node_modules/discord.js-commando/src/registry.js
2021-03-20T17:17:27.127513+00:00 app[worker.1]: - /app/node_modules/discord.js-commando/src/client.js
2021-03-20T17:17:27.127513+00:00 app[worker.1]: - /app/node_modules/discord.js-commando/src/index.js
2021-03-20T17:17:27.127513+00:00 app[worker.1]: - /app/index.js
2021-03-20T17:17:27.127514+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2021-03-20T17:17:27.127515+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2021-03-20T17:17:27.127515+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-20T17:17:27.127515+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:88:18)
2021-03-20T17:17:27.127516+00:00 app[worker.1]:     at Object.<anonymous> (/app/commands/music/play.js:11:5)
2021-03-20T17:17:27.127516+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-20T17:17:27.127516+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-20T17:17:27.127517+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-20T17:17:27.127517+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-20T17:17:27.127517+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:952:19) {
2021-03-20T17:17:27.127518+00:00 app[worker.1]:   code: 'MODULE_NOT_FOUND',
2021-03-20T17:17:27.127518+00:00 app[worker.1]:   requireStack: [
2021-03-20T17:17:27.127518+00:00 app[worker.1]:     '/app/commands/music/play.js',
2021-03-20T17:17:27.127519+00:00 app[worker.1]:     '/app/node_modules/require-all/index.js',
2021-03-20T17:17:27.127519+00:00 app[worker.1]:     '/app/node_modules/discord.js-commando/src/registry.js',
2021-03-20T17:17:27.127519+00:00 app[worker.1]:     '/app/node_modules/discord.js-commando/src/client.js',
2021-03-20T17:17:27.127520+00:00 app[worker.1]:     '/app/node_modules/discord.js-commando/src/index.js',
2021-03-20T17:17:27.127520+00:00 app[worker.1]:     '/app/index.js'
2021-03-20T17:17:27.127520+00:00 app[worker.1]:   ]
2021-03-20T17:17:27.127521+00:00 app[worker.1]: }
2021-03-20T17:17:27.276967+00:00 heroku[worker.1]: Process exited with status 1
2021-03-20T17:17:27.373771+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by galnir** [comment]
2021-03-20T17:17:27.127508+00:00 app[worker.1]: Error: Cannot find module '../../options.json'

Make sure the modified file is at the right place(inside the 'music' directory) or that options.json actually exists

**Comment by muhitrhn** [comment]
Aah, i forgot about that, accidentally deleted it. okay now i have it in place but the song won’t play. And there’s a new error in console @galnir @Bacon-Fixation - 

> 2021-03-20T18:55:33.185466+00:00 app[worker.1]: (node:23) UnhandledPromiseRejectionWarning: TypeError: message.guild.resetMusicDataOnError is not a function
2021-03-20T18:55:33.185467+00:00 app[worker.1]:     at StreamDispatcher.<anonymous> (/app/commands/music/play.js:358:27)
2021-03-20T18:55:33.185468+00:00 app[worker.1]:     at StreamDispatcher.emit (events.js:327:22)
2021-03-20T18:55:33.185468+00:00 app[worker.1]:     at streamError (/app/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:82:14)
2021-03-20T18:55:33.185479+00:00 app[worker.1]:     at PassThrough.<anonymous> (/app/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:88:67)
2021-03-20T18:55:33.185480+00:00 app[worker.1]:     at PassThrough.emit (events.js:315:20)
2021-03-20T18:55:33.185480+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-20T18:55:33.185481+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-03-20T18:55:33.185562+00:00 app[worker.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-03-20T18:55:33.185949+00:00 app[worker.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bacon-Fixation** [comment]
I haven't been able to replicate this error even on a Heroku build. 

You can also try `npm clean-install` it will remove the modules folder and reinstall.

Much Love
-Bacon

**Comment by muhitrhn** [comment]
It worked after a redo! Thank you so much @Bacon-Fixation @galnir
