### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by modyamash** [galnir/Master-Bot#49]
```
PS E:\Elite Online\elite bot\Community Bots\Master-Bot-master> node .
internal/modules/cjs/loader.js:1181
    throw err;
    ^

SyntaxError: E:\Elite Online\elite bot\Community Bots\Master-Bot-master\config.json: Unexpected token / in JSON at position 21
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1178:22)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\Elite Online\elite bot\Community Bots\Master-Bot-master\index.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
PS E:\Elite Online\elite bot\Community Bots\Master-Bot-master>
```

**Comment by zoranzoki21** [comment]
Hello @modyamash, what is content of related line?

**Comment by modyamash** [comment]
> Hello @modyamash, what is content of related line?

Config.json

**Comment by galnir** [comment]
Your error is in the config.json file, you probably didn't place an API key correctly. Make sure it's between " "
