### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [galnir/Master-Bot#596]
C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\info.js:75
      throw Error(`Error parsing info: ${err.message}`);
            ^

Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\info.js:75:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.getBasicInfo (C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\info.js:84:22)
    at async Map.getOrSet (C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\cache.js:24:19)
    at async exports.getInfo (C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\info.js:226:14)
    at async Map.getOrSet (C:\Users\karaddaddy\Desktop\friendsserver\dj\node_modules\ytdl-core\lib\cache.js:24:19)
Emitted 'error' event on PassThrough instance at:
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by galnir** [comment]
Try using the new version of the bot and let me know if the issue persists
