### ISSUE TITLE
song playing error

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#60]
Whenever I try to play a song, I get this error,
TypeError: fields.flat is not a function
I only get this error after responding with the song query.
I am hosting my bot on glitch
![Screenshot 2020-04-30 at 12 55 09 PM](https://user-images.githubusercontent.com/64607128/80743133-1226dc00-8ae2-11ea-86e7-9ef70866e1d5.png)

**Comment by galnir** [comment]
Update your nodejs version to v12 atleast

**Comment by Natemo6348** [comment]
it worked, thank you

**Comment by Natemo6348** [comment]
Now it stays silent and I get this error,

TypeError: Cannot convert "null" to int
/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.registry.npmjs.org/opusscript/0.0.7/node_modules/opusscript/build/opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMEN
abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.

**Comment by galnir** [comment]
Did you follow all the requirements and installed all the things I listed in the README?

**Comment by Natemo6348** [comment]
Yes, I did

**Comment by galnir** [comment]
The error is from opusscript, did you clone the repo or copy existing code? Because this repo uses node-opus

**Comment by Natemo6348** [comment]
I cloned the repo, added opusscript, should I remove opusscript?

**Comment by galnir** [comment]
You don't need to add dependencies to this repo, remove opusscript, there is already node-opus in the dependency list. After you remove opusscript hit ```npm i node-opus``` to make sure the build didn't fail

**Comment by Natemo6348** [comment]
After removing opusscript and installing node-opus 3 times now, I keep getting this error saying it can't be found

Error: Could not find an Opus module! Please install @discordjs/opus, node-opus, or opusscript.
    at new OpusStream (/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.registry.npmjs.org/prism-media/1.2.1/node_modules/prism-media/src/opus/Opus.js:42:13)
    at new Encoder (/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.registry.npmjs.org/prism-media/1.2.1/node_modules/prism-media/src/opus/Opus.js:130:5)
    at AudioPlayer.playPCMStream (/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.github.com/discordjs/discord.js/d3c9384c9c47cf293858778f36da014a5a503557/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.github.com/discordjs/discord.js/d3c9384c9c47cf293858778f36da014a5a503557/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/rbd/pnpm-volume/d61bf66c-3eb5-47fc-bf00-f6750a1aee03/node_modules/.github.com/discordjs/discord.js/d3c9384c9c47cf293858778f36da014a5a503557/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
at /app/commands/music/play.js:223:12
    at processTicksAndRejections (internal/process/task_queues.js:88:5)

**Comment by Natemo6348** [comment]
I just installed @discordjs/opus and it works just fine now
