### ISSUE TITLE
/play command bug 

### ISSUE THREAD

**Issue by ChickenIQ** [galnir/Master-Bot#610]
/play command breaks when selecting the cancel option in the song picker.

Error:
DiscordAPIError: Unknown Message
    at RequestHandler.execute (/home/pi/Music-Bot-JSV13/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/pi/Music-Bot-JSV13/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager.delete (/home/pi/Music-Bot-JSV13/node_modules/discord.js/src/managers/MessageManager.js:205:5)
    at async Message.delete (/home/pi/Music-Bot-JSV13/node_modules/discord.js/src/structures/Message.js:709:5) {
  method: 'delete',
  path: '/channels/531110331003437070/messages/883393193071247490',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

**Comment by ishitajs** [comment]
I have Issues with play command too
```
Master-Bot\commands\music\play.js:766
        .getVideoByID(videos[videoIndex - 1].id)
                                             ^

TypeError: Cannot read property 'id' of undefined
    at InteractionCollector.<anonymous> (D:\Github\Discord v13\Earth\commands\music\play.js:766:46)
    at InteractionCollector.emit (node:events:406:35)
    at InteractionCollector.handleCollect (D:\Github\Discord v13\Earth\node_modules\discord.js\src\structures\interfaces\Collector.js:108:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
When running the play command, bot is displaying select menu with undefined as options. Once we selected something it pops the above error in console and this is crashing the entire bot..
![](https://cdn.discordapp.com/attachments/883408234625515560/883408331828506724/unknown.png)

**Comment by galnir** [comment]
@ChickenIQ Pull the new changes it should be solved

@ishitajs Did you generate a valid API key?

**Comment by ishitajs** [comment]
> @ishitajs Did you generate a valid API key?
Yes obv i have generated my api key yesterday night

**Comment by galnir** [comment]
@ishitajs If when you try to play a song using its YouTube URL (/play example.com) it fails, then the problem is with the API key you generated. Let me know if it also fails when you try that
