### ISSUE TITLE
Music Trivia Song Showing random Output

### ISSUE THREAD

**Issue by DevEvelynn** [galnir/Master-Bot#618]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Bot Will not start
**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
The Bot to run
**Screenshots**
![image](https://user-images.githubusercontent.com/45043402/132996514-3164ee13-324a-418e-b2d5-ff6446809659.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows
 - Node Version(Should be v14 atleast): 16.9.1
 - Is python 2.7 installed?: yes 3.8.7 
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**

**Comment by galnir** [comment]
You may have forgot to put a comma after a line in your config.json
If you can, take a screenshot of your config.json and **make sure to blur all your api keys**

**Comment by DevEvelynn** [comment]
turns out i forgot a , after the Token

**Comment by DevEvelynn** [comment]
```
AudioPlayerError: Status code: 410
    at ClientRequest.<anonymous> (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\miniget\dist\index.js:210:27)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23) {
  resource: AudioResource {
    playbackDuration: 0,
    started: false,
    silenceRemaining: -1,
    edges: [ [Object], [Object] ],
    playStream: OggDemuxer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _remainder: null,
      _head: null,
      _bitstream: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    metadata: null,
    silencePaddingFrames: 5,
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      subscribers: [Array],
      _state: [Object],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    }
  }
}
```
Not sure what that means

**Comment by DevEvelynn** [comment]
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.reply (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5) {
  method: 'post',
  path: '/interactions/886670256800665710/aW50ZXJhY3Rpb246ODg2NjcwMjU2ODAwNjY1NzEwOmVmdW5PU0lRQzI0VVJyd290V09TMkh5dWJjQjZyMU85dldkdlgxOUZpc25KQXh1YURjaEhHaUVlMllhNXZmTWlwTTRDZDBPd2htYzZFUVp2dktkWDBwYldxa3pBUHc1WkFIUlJHYjZCUGVTUTBWT3lNc3R0eGdJSHFOU05QSFRU/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\rest\RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.reply (C:\Users\Bently21\Downloads\Master-Bot-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5) {
  method: 'post',
  path: '/interactions/886670256800665710/aW50ZXJhY3Rpb246ODg2NjcwMjU2ODAwNjY1NzEwOmVmdW5PU0lRQzI0VVJyd290V09TMkh5dWJjQjZyMU85dldkdlgxOUZpc25KQXh1YURjaEhHaUVlMllhNXZmTWlwTTRDZDBPd2htYzZFUVp2dktkWDBwYldxa3pBUHc1WkFIUlJHYjZCUGVTUTBWT3lNc3R0eGdJSHFOU05QSFRU/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 4,
      data: {
        content: ':x: Request to find a doggo failed!',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}

```
bot then proceded to crash

**Comment by DevEvelynn** [comment]
@galnir

**Comment by galnir** [comment]
This looks like it crashed after you used /dog command?

**Comment by DevEvelynn** [comment]
yes

**Comment by DevEvelynn** [comment]
i was doing trivia and then i did /dog then the bot go brrrrrrrrr

**Comment by galnir** [comment]
I'll look into it

**Comment by DevEvelynn** [comment]
ty

**Comment by galnir** [comment]
@DevEvelynn 51495a5 should solve it for you. Let me know if it doesn't

**Comment by DevEvelynn** [comment]
@galnir Also the skip in trivia doesn't work at times
