### ISSUE TITLE
The bot doesn't start

### ISSUE THREAD

**Issue by FrancimanLst** [galnir/Master-Bot#625]
When i try to run the command `node index.js` i get this error:

```
C:\Users\Utente\Documents\Master-Bot-main>node index.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'timers/promises'
Require stack:
- C:\Users\Utente\Documents\Master-Bot-main\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js
- C:\Users\Utente\Documents\Master-Bot-main\node_modules\@discordjs\rest\dist\lib\RequestManager.js
- C:\Users\Utente\Documents\Master-Bot-main\node_modules\@discordjs\rest\dist\index.js
- C:\Users\Utente\Documents\Master-Bot-main\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\Utente\Documents\Master-Bot-main\node_modules\←[4m@discordjs←[24m\rest\dist\lib\handlers\SequentialHandler.js:6:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Utente\\Documents\\Master-Bot-main\\node_modules\\@discordjs\\rest\\dist\\lib\\handlers\\SequentialHandler.js'←[39m,
    ←[32m'C:\\Users\\Utente\\Documents\\Master-Bot-main\\node_modules\\@discordjs\\rest\\dist\\lib\\RequestManager.js'←[39m,
    ←[32m'C:\\Users\\Utente\\Documents\\Master-Bot-main\\node_modules\\@discordjs\\rest\\dist\\index.js'←[39m,
    ←[32m'C:\\Users\\Utente\\Documents\\Master-Bot-main\\index.js'←[39m
  ]
}
```
 - OS: Windows
 - Node Version(Should be v14 atleast): 14.17.6
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): locally

I hope you can help me,
Francesco.

**Comment by Bacon-Fixation** [comment]
Howdy,

with the recent discord.js v13 changes the node and python versions are different

try with Node V16  https://nodejs.org/en/download/current/
Python 3 https://www.python.org/downloads/

then run `npm ci --prodution` again

i hope this helps 

Much Love
-Bacon

**Comment by FrancimanLst** [comment]
Thank you for the help, now i fixed!
-Francesco

**Comment by FrancimanLst** [comment]
The problem persist on Heroku and i don't any idea on how to fix it there :/

**Comment by Princevikas** [comment]
im having the same error in heroku

**Comment by galnir** [comment]
@FrancimanLst @Princevikas Are you sure your Node.js version in Heroku is 16+?

**Comment by FrancimanLst** [comment]
@galnir I just tried to upgrade the node version to 16+ but it still giving me problem... Maybe i did something wrong, here is my package.json modified:
```
{
  "name": "master-bot",
  "version": "1.0.0",
  "description": "a discord music bot with guild , gifs and misc commands",
  "main": "index.js",
  "scripts": {
    "start": "node .",
    "test": "jest",
    "test:watch": "jest --watch",
    "pretest": "eslint --ignore-path .gitignore ."
  },
  "author": "Nir Gal",
  "license": "ISC",
  "dependencies": {
    "@discordjs/builders": "^0.5.0",
    "@discordjs/opus": "^0.6.0",
    "@discordjs/rest": "^0.1.0-canary.0",
    "@discordjs/voice": "^0.6.0",
    "@vitalets/google-translate-api": "^7.0.0",
    "cheerio": "^1.0.0-rc.10",
    "discord-api-types": "^0.22.0",
    "discord.js": "^13.1.0",
    "discord.js-pages": "^1.3.0",
    "ffmpeg": "0.0.4",
    "ffmpeg-static": "^4.4.0",
    "iso-639-1": "^2.1.9",
    "libsodium-wrappers": "^0.7.9",
    "mongoose": "^5.13.5",
    "spotify-url-info": "^2.2.3",
    "youtube-dl-exec": "^1.2.4",
    "youtube-sr": "^4.1.7",
    "ytdl-core": "^4.9.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^5.16.0",
    "eslint-plugin-jest": "^24.4.0",
    "jest": "^27.1.1",
    "nodemon": "^1.19.4",
    "prettier": "^1.19.1"
  },
  "engines": {
    "node": "16.x",
    "npm": ">=6.0.0"
  }
}
```

**Comment by KiyoshiKunCool** [comment]
Just add:

"engines": {
    "node": "16.9.0"
     }

it works on my Heroku :D

**Comment by FrancimanLst** [comment]
@KiyoshiKunCool Ok that worked, thank you. But now for some reasons Heroku doesn't find anymore my config.file....
```
2021-09-18T17:22:50.342988+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2021-09-18T17:22:50.343005+00:00 app[worker.1]:   throw err;
2021-09-18T17:22:50.343005+00:00 app[worker.1]:   ^
2021-09-18T17:22:50.343005+00:00 app[worker.1]: 
2021-09-18T17:22:50.343006+00:00 app[worker.1]: Error: Cannot find module './config.json'
2021-09-18T17:22:50.343006+00:00 app[worker.1]: Require stack:
2021-09-18T17:22:50.343006+00:00 app[worker.1]: - /app/index.js
2021-09-18T17:22:50.343007+00:00 app[worker.1]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-09-18T17:22:50.343007+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2021-09-18T17:22:50.343007+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2021-09-18T17:22:50.343008+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:94:18)
2021-09-18T17:22:50.343008+00:00 app[worker.1]:     at Object.<anonymous> (/app/index.js:5:41)
2021-09-18T17:22:50.343008+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2021-09-18T17:22:50.343008+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2021-09-18T17:22:50.343009+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)
2021-09-18T17:22:50.343009+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-09-18T17:22:50.343009+00:00 app[worker.1]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
2021-09-18T17:22:50.343010+00:00 app[worker.1]:   code: 'MODULE_NOT_FOUND',
2021-09-18T17:22:50.343010+00:00 app[worker.1]:   requireStack: [ '/app/index.js' ]
2021-09-18T17:22:50.343010+00:00 app[worker.1]: }
```

**Comment by Bacon-Fixation** [comment]
Howdy,

For heroku you need to add this to the `package.json`, so it will deploy useing the correct stack, python 3 is on all stacks

```
  "engines": {
    "node": "16.x"
  },
```

should look something like this then redeploy your project
![image](https://user-images.githubusercontent.com/12632936/133906999-4d924d17-c632-493e-b6c8-7ba1d9d8a08b.png)

currently testing if this will conflicts with other build methods before i make a pr
heroku defaults to 14 

[more info here](https://devcenter.heroku.com/articles/nodejs-support#node-js-runtimes)

Much Love
-Bacon

**Comment by KiyoshiKunCool** [comment]
The "package.json" will like this:
![Ảnh chụp màn hình 2021-09-19 083513](https://user-images.githubusercontent.com/69381154/133912699-fd92866b-7fa2-45ad-80a9-06e638e00bf3.png)

And I set config the "buildpacks" like this:
(Cmd: "heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#latest -a your-app" | Change "your-app" to your app name like "mastet-bot")

![Ảnh chụp màn hình 2021-09-19 083135](https://user-images.githubusercontent.com/69381154/133912646-d0d1df09-1c95-44ab-bcad-0e5ab6d468d7.png)

And it works smoothly :33
#KiyoshiKunCool

**Comment by FrancimanLst** [comment]
I did all that again and it leaves me again with the error message 'Cannot find module './config.json'

**Comment by KiyoshiKunCool** [comment]
@FrancimanLst Did you create Mongoose database and put the "mongo_URI" yet??

**Comment by FrancimanLst** [comment]
@KiyoshiKunCool Yes, if i start the bot locally it works fine, the problem is when i try to do it on Heroku

**Comment by MrUnstable** [comment]
Tried to recreate this whole thing and basically what fixed it for me is forking a private copy of Master-Bot , adding config.json and Procfile to private fork and turning auto deployment (main branch make sure both config and Procfile are also uploaded in main branch)

**Comment by galnir** [comment]
@FrancimanLst The config.json needs to be at the root directory of the project, at the same level index.js is

**Comment by FrancimanLst** [comment]
I'm stupid, i didn't add config.json to the fork on github... Sorry guys for bothering you and thanks for the help! Now it works and that's the worth part!
