### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#66]
So I decided to clone the repository again so I could undo my changes that broke in the first place, but now every time I try to run a command, I get this error and I don't know what's causing it.
(node:17592) UnhandledPromiseRejectionWarning: TypeError: str.replace is not a function
    at escapeRegex (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/Commando/bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc/node_modules/discord.js-commando/src/util.js:2:13)
    at CommandDispatcher.buildCommandPattern (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/Commando/bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc/node_modules/discord.js-commando/src/dispatcher.js:292:26)
    at CommandDispatcher.parseMessage (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/Commando/bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc/node_modules/discord.js-commando/src/dispatcher.js:257:43)
    at CommandDispatcher.handleMessage (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/Commando/bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc/node_modules/discord.js-commando/src/dispatcher.js:120:18)
    at CommandoClient.<anonymous> (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/Commando/bdbd84e2a978322f3af12c21e729eb7b7cd4a3dc/node_modules/discord.js-commando/src/client.js:64:51)
    at CommandoClient.emit (events.js:196:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/discord.js/766b91d306e93ef2e58bc52c9be5633b1092277a/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/discord.js/766b91d306e93ef2e58bc52c9be5633b1092277a/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/discord.js/766b91d306e93ef2e58bc52c9be5633b1092277a/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/29dc74f9-fe95-408f-b145-64e0ea45c0d1/node_modules/.github.com/discordjs/discord.js/766b91d306e93ef2e58bc52c9be5633b1092277a/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
(node:17592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by galnir** [comment]
What command are you trying to use? Did you hit 'npm i' after cloning?

**Comment by Natemo6348** [comment]
I did do 'npm i' after cloning, and I was trying to use play, but I'm no longer getting the error now. Still not sure what caused it.

**Comment by galnir** [comment]
@Natemo6348 Might be related to a bug that was resolved in one of the dependencies(ytdl-core)

**Comment by Natemo6348** [comment]
Oh ok, that would make sense
