### ISSUE TITLE
npm run dev error suspect

### ISSUE THREAD

**Issue by amirshah2935** [galnir/Master-Bot#694]
Hi, im having issue after running the npm run dev where the error as below:-

PS C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan> npm run dev

> master-bot@1.0.0 dev
> npm run build && npm run start

> master-bot@1.0.0 build
> tsc

> master-bot@1.0.0 start
> node dist/index.js

[INFO] ApplicationCommandRegistries: Initializing...
[WARN] ApplicationCommandRegistries: Failed to fetch guild commands for guild "Atyn's server" (784864401844076584). Make sure to authorize your application with the "applications.commands" scope in that guild.
[WARN] ApplicationCommandRegistries: Failed to fetch guild commands for guild "athaa's server" (839568436095090738). Make sure to authorize your application with the "applications.commands" scope in that guild.
[INFO] ApplicationCommandRegistry[baka] Successfully created chat input command "baka" with id "961854659608330280". You should add the id to the "idHints" property of the register method you used!
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: Error: getaddrinfo ENOTFOUND lavalink
    at Connection._onerror (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\lavaclient\dist\lib\node\Connection.js:138:29)
    at WebSocket.onError (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\ws\lib\event-target.js:220:18)
    at WebSocket.emit (node:events:526:28)
    at emitErrorAndClose (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\ws\lib\websocket.js:922:13)
    at ClientRequest.<anonymous> (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\ws\lib\websocket.js:781:5)
    at ClientRequest.emit (node:events:526:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
Emitted 'error' event on Node instance at:
    at Connection._onerror (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\lavaclient\dist\lib\node\Connection.js:138:15)
    at WebSocket.onError (C:\Users\Admin\Dropbox\Amir\BOT\penyanyijalanan\node_modules\ws\lib\event-target.js:220:18)
    [... lines matching original stack trace ...]
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)

**Comment by galnir** [comment]
Did you follow the instructions in the README?
