### ISSUE TITLE
Bot joins call after a song is requested, and quits when the song is about to play

### ISSUE THREAD

**Issue by barateza** [galnir/Master-Bot#818]
**Describe the bug**
Bot joins call after a song is requested, and quits when the song is about to play.

**To Reproduce**
- use /play + query
- the song is about to be reproduced, the bot joins the call, then quits the call.

**Expected behavior**
The bot should stay in the call and play the song.

**Screenshots**
N/A

**Desktop:**
- OS: Almalinux 8.9
- Node.js Version(Should be v16 at least): v20.12.0
- Is python 2.7 installed?: no, Python 3.6.8
- How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Additional context**
1. The bot seems to be running just fine otherwise, despite what it just said...
![image](https://github.com/galnir/Master-Bot/assets/3647085/f841a2e9-bae9-47f6-8019-9aea2b90e34f)

2. When requested from YouTube, the music seems to be queued, and controls appear, but the song does not play and the bot kicks itself.

    ![image](https://github.com/galnir/Master-Bot/assets/3647085/8a3a7919-6214-47cb-838d-eae22ab4ccad)

    Lavalink:

```
2024-03-29 06:00:19.758  INFO 1244651 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"826863331474145361","sessionId":"643d73e4eaa52e5e1aa755489e046e25","event":{"token":"[censored]","guild_id":"[censored]","endpoint":"brazil11038.discord.media:443"}}
2024-03-29 06:00:19.831  INFO 1244651 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2gF_ZIBiKOw%26t%3D13s, client=127.0.0.1
2024-03-29 06:00:45.010  INFO 1244651 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Já que me ensinou a beber Muffled 1 hora"
2024-03-29 06:00:45.450  INFO 1244651 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Já que me ensinou a beber Muffled 1 hora
2024-03-29 06:00:45.454  INFO 1244651 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=ytsearch%3AJ%C3%A1%20que%20me%20ensinou%20a%20beber%20Muffled%201%20hora, client=127.0.0.1
2024-03-29 06:00:45.489  INFO 1244651 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"826863331474145361","volume":100}
2024-03-29 06:00:45.490  INFO 1244651 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","track":"QAAAjAIAKUrDoSBxdWUgbWUgZW5zaW5vdSBhIGJlYmVyIE11ZmZsZWQgMSBob3JhAAlFc3RhUm9zY2EAAAAAADfogAALMmdGX1pJQmlLT3cAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj0yZ0ZfWklCaUtPdwAHeW91dHViZQAAAAAAAAAA","guildId":"[censored]"}
2024-03-29 06:00:46.173  INFO 1244651 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"[censored]"}
``` 

3. Spotify also has a playing issue.
    3.1 bot joins the channel
    3.2 shows the error message:
    `:x: Couldn't find what you were looking for :(`
    3.3 bot leaves the channel

    The output from lavalink server for Spotify:
(i have added client id and secret to .env, bot is in development mode, APIs used are Web API and Web Playback SDK)
```
2024-03-29 05:37:41.241  INFO 1237240 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/episode/5ZnTuT7DhPKVW8m2tkcOik?si=11de7ff2a24e4dda"
2024-03-29 05:37:41.570 ERROR 1237240 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:35) ~[lavaplayer-1.5.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:73) ~[lavaplayer-1.5.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-1.5.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-1.5.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-1.5.3.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.3
  os.arch: amd64
  os.name: Linux
  os.version: 4.18.0-513.11.1.el8_9.x86_64
  java.vendor: Azul Systems, Inc.
  java.version: 13.0.14
  java.runtime.version: 13.0.14+5-MTS
  java.vm.version: 13.0.14+5-MTS
``` 

4. SoundCloud reproduction is fine, there are no issues whatsoever.

5. Depending on the query sometimes I will receive this error:

    ![image](https://github.com/galnir/Master-Bot/assets/3647085/2f0ae3a3-e391-479e-910b-9183d42b4122)

And the prompt will show 

```
@master-bot/bot:dev: Client Listener TRPCClientError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
@master-bot/bot:dev: Client Listener TRPCClientError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
@master-bot/bot:dev: Client Listener TRPCClientError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

**Comment by Bacon-Fixation** [comment]
Howdy @barateza, 

my apologise for delayed response, seems that youtube calls using LavaLink V3.x are not working currently, I am looking into updating to Lavalink v4 since it's been released, and currently the lavalink-client module in the package.json doesn't support LavaLink V4 yet.

it may take some time before a fix is released, as it could possibly be an extensive update to get youtube/spotify links usable again

Much Love
-Bacon

**Comment by Natemo2625** [comment]
I currently have YouTube links working, haven't looked at Spotify yet (Using Lavalink v3 and lavaclient 4.1.1)
Edit: Spotify links for songs seem to work fine (redirecting to youtube), although one thing I did notice is podcasts may not work (idk if that was always the case or not) as the one I tried gave me an "Unknown file format" warning in Lavalink logs

**Comment by Natemo2625** [comment]
Lavalink v3 will no longer work, in the process of attempting a v4 update on my local instance of Master-Bot, but I don't know when or if I'll succeed

**Comment by PhantomNimbi** [comment]
This is being worked on in my current workstream. You can see my progress in the issue below:

- #828

**Comment by PhantomNimbi** [comment]
## ✅ Update: Bot Joining Then Quitting Voice — Resolved

The root cause of the bot joining the voice call and then quitting right before playback is addressed in the maintenance work. This was caused by the legacy Lavalink v3 engine plus broken voice packet routing to `lavalink-client`.

---

### 🔧 What Fixed It

- **Voice Gateway Packet Routing** (`Stage 16`): Fixed the Discord voice connection failure by changing `this.ws.on()` → `this.on('raw')` in `ExtendedClient.ts`. This ensures the `VOICE_SERVER_UPDATE` header actually reaches `lavalink-client`, so Lavalink establishes a stable voice connection that no longer drops when playback begins.
- **Lavalink v4 Engine Migration** (`Stage 4`): Upgraded from the legacy `lavaclient` v3 (which no longer works with YouTube) to **`lavalink-client` v2** against Lavalink v4, restoring reliable YouTube/Spotify stream extraction.
- **Turnstile Play Fix**: Added `queue.next()` triggering on `/play` when idle, and ensured the player stays connected through track playback (`Stage 16`).

---

### 🔗 PR Status

This fix is bundled into the open maintenance PR:

**PR #829** → https://github.com/galnir/Master-Bot/pull/829

- **Branch**: `PhantomNimbi:main`
- **Status**: ✅ Open & Ready for Review
- **Summary**: `feat: modernize monorepo, upgrade Lavalink v4 & cipher, enhance dashboard, and fix auth/tooling`

This issue is now **resolved** pending PR #829's merge.
