### ISSUE TITLE
Missing Permissions from Discord API

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#85]
**Describe the bug**
There is this "Missing Permissions" error in the logs every few minutes, although the bot functions normally. In my testing, I have given the bot administrator in my test server. This may be occuring in other servers that the bot is in, but it seems to be missing a catch.

**To Reproduce**
1. I don't know what happened so I don't know how to repro.

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/49682825/83287414-362a2a00-a214-11ea-8720-324f4e3e28c3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]: Probably some distro of Linux (Heroku)
 - Node Version(Should be v12 atleast): 12.17.0
 - Are python 2.7 and Ffmpeg installed?: Yes.
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**
Here is the full error.
```
2020-05-29T17:43:26.423082+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
2020-05-29T17:43:26.423105+00:00 app[worker.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
2020-05-29T17:43:26.423109+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-05-29T17:43:26.423110+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-29T17:43:26.423163+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by galnir** [comment]
I can't figure out why it happened if you don't know how it happened. Did you attempt to use a guild command(ban/kick)?

**Comment by ThaddeusKKR** [comment]
You've got a point. I did not use a guild command. I'll do some further testing with an instance that is only in my test server so that I know that it is not originating from commands used in other servers.

**Comment by galnir** [comment]
Did you give it admin on the invitation screen? And if it has a role make sure the role is the one at the very top at the roles list(In server settings)

**Comment by galnir** [comment]
Did you install the dependencies correctly? And did you modify anything in the code?

**Comment by ThaddeusKKR** [comment]
I ran `npm i` and I did not modify anything in the kick command. The only thing I modified was the bot's presence and turned on the `prefix` and `eval` command.

**Comment by galnir** [comment]
Is the bot higher in the hierarchy than the user you are trying to kick? Like I said in roles

**Comment by ThaddeusKKR** [comment]
Oh I see now, the bot had the same role as the test user. Thanks!
